### PR TITLE
auto select subplebbit on post if routed from subplebbit

### PR DESCRIPTION
**Pull request by shammils**
Rough draft of feature request `clicking create post when on a subplebbit page should automatically select that subplebbit` which is not ready to merge; just want to get input if this is the right direction.

I noticed the create post route supported addresses in the URL and went with that
https://github.com/plebbit/plebbit-react/blob/fb036ea0b67deb33f048da373f095da01d0676dd/src/App.js#L20

I pass the address to the CreatePostBar module, set the route accordingly then pull the address out of the path part in the CreatePost module. I set the address during initialization so the useEffect is pointless.

I think this would work, didnt have to access indexdb, history and global context. needs a lot of cleanup.
Peek 2022-08-27 21-12

### CODE REVIEW

**Comment by estebanabaroa** [comment]
using #/p/subplebbit.address/submit is a good idea

**Comment by Abydin** [comment]
Nice 👍

**Comment by shammils** [comment]
Peek 2022-08-28 08-56
final draft, fully cleaned up.

**Review by Abydin — APPROVED** [review]
👍

**Pull request merged**
